CANDIDATE_COINS = ["BTC", "ETH", "BNB", "ADA", "SOL", "XRP", "AVAX", "TRX", "DOT", "MATIC", "LINK", "TON", "LTC", "BCH", "ETC", "UNI", "XLM", "FIL", "XMR", "FTM"]
WEIGHTS_STEP_PRECISION_PERCENT = 20 # must be a divisor of 100
SIMULATION_START_DATE = "2020-01-01"
SIMULATION_END_DATE = "2021-03-01"
START_WALLET_SIZE_USD = 1000
